### ISSUE TITLE
Array of peaks

### ISSUE THREAD

**Issue by aiyk** [SoundstripeEngineering/react-audio-waveform#2]
can't figure how to generate the array of peaks. can someone please point me in the right direction. 
thanks.

**Comment by Jchinonso** [comment]
You can follow this tutorial on how to do it https://getstream.io/blog/generating-waveforms-for-podcasts-in-winds-2-0/

**Comment by TrevorHinesley** [comment]
Apologies for the late reply. @Jchinonso nailed it. You can also use https://github.com/bbc/audiowaveform to extract peak data.

**Comment by drzajwo** [comment]
Hi,
Sorry for "reopening" issue. I'm implementing waveform to project I'm working on.
For now I'm using [bbc/audiowaveform data](https://gist.githubusercontent.com/PawelGt/8d0c07d860df8efbaccf7c49c3d78647/raw/0f2c7ce819d555b1866eeb9b41b665b7f54ad297/waveform.json) and scale it like below:
```
  const clamp = (num, min, max) => {
    return num <= min ? min : num >= max ? max : num;
  };

  const scaleData = () => {
    // song can be 8 or 16 bits
    const max = Math.pow(2, bits - 1);
    const scaled = data.map((val, index) => {
      let scaledVal = val / max;
      // Not sure how to handle negative values...
      scaledVal = scaledVal < 0 ? scaledVal * -1 : scaledVal;
      return clamp(scaledVal, -1, 1);
    });
    return scaled;
  };
```
Where `data` and `bits` are fetched from bbc data. This helps me to easily get values in rage [-1, 1] however you guys support values in range [0, 1] so in my code I'm converting negative values to positive (I'm pretty sure it's wrong :D ).

@Jchinonso In this article image for most important part for me is missing...

**Comment by larrywal** [comment]
@TrevorHinesley ... I want to generate peaks dynamically for a user chosen file.  Do you know of any component that will do that so I can hook it up to the peaks property?

**Comment by TrevorHinesley** [comment]
Hi @larrywal, are you referring to generating peaks in the browser from a user selected file, rather than server side? It’s recommended to do this server side with a library like https://github.com/bbc/audiowaveform. 

This is worth referencing for reasons why: https://jessieji.com/2019/why-generating-waveform-for-a-large-audio-file-may-not-be-a-good-thing

**Comment by larrywal** [comment]
Got it yes that's what I was referring to.  Very helpful, thanks.  I'll take a read through.

**Comment by larrywal** [comment]
Thanks - made sense when reading.  Any chance you've come across a nodeJS server solution I could serve from express?  What I'm hoping to do is have the user pick an audio file using an <input type="file, then I guess send that to my node express server,  transform that into peaks, and send back to client to render into a wave form.  Hoping that's a common pattern with a repo I can copy from or reuse...

**Comment by TrevorHinesley** [comment]
Are you only trying to display waveforms at the time of file selection, or is this file being stored on your server and accessed later on as well?

Either way, you can simply use the audiowaveform library I linked to, and execute a shell command from Node to run it and generate your file of peaks.

**Comment by larrywal** [comment]
Appreciate the reply - except I don't think I can execute shell commands.  This is a web app connected to a node js express server. The user picks a sound file...then I want to show the waveform to the user. 

I don't think I can execute shell commands in a node express response to the client.  I need to generate the peaks in JavaScript while I'm building the servers response.

**Comment by TrevorHinesley** [comment]
@larrywal any server side framework should be able to execute command line scripts. Give this a shot: https://stackoverflow.com/questions/26806247/can-you-call-a-shell-script-from-an-expressjs-app

**Comment by TrevorHinesley** [comment]
Also, I don’t know enough about your use case but if the files are small enough and you don’t care about loading the whole file into memory before waveforms can be generated, something like wavesurfer might work best since you don’t need to generate peaks separately. Keep in mind doing it this way means any time a user streams the file, the entire file has to download into browser memory to show the waveform: https://wavesurfer-js.org/

**Comment by khalil0525** [comment]
> You can follow this tutorial on how to do it https://getstream.io/blog/generating-waveforms-for-podcasts-in-winds-2-0/

This will be performed on the client-side, right?
